### ISSUE TITLE
Text for DUALITY LIGHTING

### ISSUE THREAD

**Issue by dssong02** [amaidah/ds-portfolio#3]
Duality Lighting
Packaging

Duality Lighting specializes in LED lighting solutions for residential and commercial use. Packaging for their new Novaflux PAR30 required an easily identifiable product. The cluttered packaging design of most lighting products by major competitors lends itself to products that are off-putting and hard to differentiate. We decided to showcase the Novaflux PAR30 through subtle, minimalist design making it easier for it to stand out within the industry.

**Comment by amaidah** [comment]
WHO IS WE?

**Comment by dssong02** [comment]
Myself & Client

**Comment by amaidah** [comment]
WHERE ARE CREDITS?

**Comment by dssong02** [comment]
No credits need for this one.

**Comment by amaidah** [comment]
hmm, so credits display has to have logic

**Comment by amaidah** [comment]
So you want credits to be hidden if there's no credit to be given?

**Comment by dssong02** [comment]
Well, I was just hoping that could be just a text field so that it would be a bit more flexible.

**Comment by amaidah** [comment]
fkn that is a database design that u do on STEP 1 U FUCKING IDIOT
